import {
  Studio,
  TeamMember,
  Client,
  Project,
  Quotation,
  Payment,
  Gallery,
  GalleryImage,
  CalendarEvent,
  PortfolioProfile,
  Notification,
  ActivityLog,
  StorageUsage,
  PhotoSelectionState,
  Contract,
  ContractClause,
  Invoice,
} from "@/lib/types";
import { STORAGE_PLANS, calculateStorageWarning } from "@/lib/storage";

// ============================================================================
// REALISTIC INITIAL MOCK DATA
// ============================================================================

export const INITIAL_STUDIO: Studio = {
  id: "studio-1",
  name: "UIKEY AI Studio",
  ownerName: "Arjun Mehta",
  city: "Mumbai",
  serviceArea: "Mumbai · Goa · Worldwide",
  phone: "+91 98201 98201",
  whatsappNumber: "+91 98201 98201",
  email: "arjun@uikeystudio.com",
  upiId: "uikeystudio@upi",
  defaultWatermark: "PROOF ONLY · UIKEY AI STUDIO",
  watermarkOpacity: 0.28,
  planId: "standard",
  createdAt: "2024-01-15T10:00:00Z",
};

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: "tm-1",
    studioId: "studio-1",
    name: "Arjun Mehta",
    email: "arjun@uikeystudio.com",
    role: "Owner",
    phone: "+91 98201 98201",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    joinedDate: "2024-01-15",
    permissions: {
      canViewProjects: true,
      canEditProjects: true,
      canUploadPhotos: true,
      canManageClients: true,
      canCreateQuotations: true,
      canVerifyPayments: true,
      canViewAnalytics: true,
      canManageTeam: true,
    },
  },
  {
    id: "tm-2",
    studioId: "studio-1",
    name: "Vikram Rathore",
    email: "vikram@uikeystudio.com",
    role: "Photographer",
    phone: "+91 98111 22334",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    joinedDate: "2024-02-01",
    permissions: {
      canViewProjects: true,
      canEditProjects: true,
      canUploadPhotos: true,
      canManageClients: false,
      canCreateQuotations: false,
      canVerifyPayments: false,
      canViewAnalytics: false,
      canManageTeam: false,
    },
  },
  {
    id: "tm-3",
    studioId: "studio-1",
    name: "Pooja Verma",
    email: "pooja@uikeystudio.com",
    role: "Editor",
    phone: "+91 98333 44556",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    joinedDate: "2024-03-10",
    permissions: {
      canViewProjects: true,
      canEditProjects: true,
      canUploadPhotos: true,
      canManageClients: false,
      canCreateQuotations: false,
      canVerifyPayments: false,
      canViewAnalytics: false,
      canManageTeam: false,
    },
  },
  {
    id: "tm-4",
    studioId: "studio-1",
    name: "Sameer Joshi",
    email: "sameer@uikeystudio.com",
    role: "Finance Manager",
    phone: "+91 98444 55667",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    joinedDate: "2024-04-01",
    permissions: {
      canViewProjects: true,
      canEditProjects: false,
      canUploadPhotos: false,
      canManageClients: true,
      canCreateQuotations: true,
      canVerifyPayments: true,
      canViewAnalytics: true,
      canManageTeam: false,
    },
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: "c-1",
    studioId: "studio-1",
    name: "Rhea & Kabir Kapur",
    email: "rhea.kapur@gmail.com",
    phone: "+91 98200 11223",
    whatsappNumber: "+91 98200 11223",
    eventType: "Mehendi & Sangeet",
    eventDate: "2026-10-18",
    venue: "The St. Regis Mumbai · Astor Ballroom",
    budget: 185000,
    leadSource: "Instagram Portfolio",
    status: "Booked",
    notes: "Requires drone coverage for terrace entry. Couple loves warm cinematic tones.",
    totalProjectValue: 185000,
    paidAmount: 95000,
    pendingAmount: 90000,
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-09-15T14:30:00Z",
  },
  {
    id: "c-2",
    studioId: "studio-1",
    name: "Saanvi Malhotra",
    email: "saanvi.m@outlook.com",
    phone: "+91 98765 43210",
    whatsappNumber: "+91 98765 43210",
    eventType: "Editorial Portrait",
    eventDate: "2026-10-05",
    venue: "Studio Colaba, Mumbai",
    budget: 35000,
    leadSource: "Referral from Pooja",
    status: "Booked",
    notes: "3 outfit changes. Natural window light + strobe. Black & white high contrast selections requested.",
    totalProjectValue: 35000,
    paidAmount: 20000,
    pendingAmount: 15000,
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-09-18T16:00:00Z",
  },
  {
    id: "c-3",
    studioId: "studio-1",
    name: "Isha & Aditya Nair",
    email: "isha.aditya@gmail.com",
    phone: "+91 99300 88776",
    whatsappNumber: "+91 99300 88776",
    eventType: "Wedding & Reception",
    eventDate: "2026-07-24",
    venue: "Grand Hyatt Goa",
    budget: 240000,
    leadSource: "Google Search",
    status: "Completed",
    notes: "Full multi-day coverage. Delivered complete master drive and two heirloom fine art albums.",
    totalProjectValue: 240000,
    paidAmount: 240000,
    pendingAmount: 0,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-08-30T12:00:00Z",
  },
  {
    id: "c-4",
    studioId: "studio-1",
    name: "Tara & Rohan Mehra",
    email: "tara.mehra@yahoo.com",
    phone: "+91 98199 55443",
    whatsappNumber: "+91 98199 55443",
    eventType: "Royal Wedding 3-Day",
    eventDate: "2026-11-12",
    venue: "Umaid Bhawan Palace, Jodhpur",
    budget: 380000,
    leadSource: "Wedding Planner (Krafting Memories)",
    status: "Booked",
    notes: "High profile event. Full crew of 4 (2 candid, 1 traditional, 1 cinematographic drone).",
    totalProjectValue: 380000,
    paidAmount: 150000,
    pendingAmount: 230000,
    createdAt: "2026-07-15T08:00:00Z",
    updatedAt: "2026-09-20T18:00:00Z",
  },
  {
    id: "c-5",
    studioId: "studio-1",
    name: "Ananya Deshmukh",
    email: "ananya.d@gmail.com",
    phone: "+91 98211 44778",
    whatsappNumber: "+91 98211 44778",
    eventType: "Pre-wedding Shoot",
    eventDate: "2026-10-29",
    venue: "South Mumbai Heritage Precinct",
    budget: 45000,
    leadSource: "Public Portfolio Website",
    status: "Quotation sent",
    notes: "Inquired via portfolio. Wants vintage film look + drone sunset at Marine Drive.",
    totalProjectValue: 45000,
    paidAmount: 0,
    pendingAmount: 45000,
    createdAt: "2026-09-21T09:30:00Z",
    updatedAt: "2026-09-21T10:00:00Z",
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "p-1",
    studioId: "studio-1",
    name: "Kapur · Mehendi",
    clientId: "c-1",
    clientName: "Rhea & Kabir Kapur",
    clientEmail: "rhea.kapur@gmail.com",
    clientPhone: "+91 98200 11223",
    eventType: "Mehendi & Sangeet",
    eventDate: "2026-10-18",
    venue: "The St. Regis Mumbai · Astor Ballroom",
    status: "Proofing",
    assignedPhotographer: "Arjun Mehta",
    assignedEditor: "Pooja Verma",
    quotationId: "q-1",
    quotationAmount: 185000,
    paidAmount: 95000,
    balanceAmount: 90000,
    galleryId: "g-1",
    deliveryDeadline: "2026-11-05",
    notes: "238 photos uploaded for proofing. Waiting for client to finalize album picks.",
    checklist: {
      contractAccepted: true,
      advanceReceived: true,
      shootCompleted: true,
      photosBackedUp: true,
      cullingCompleted: true,
      editingCompleted: true,
      galleryUploaded: true,
      clientSelectionReceived: false,
      finalPaymentReceived: false,
      originalsDelivered: false,
    },
    photoCount: 238,
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-09-20T12:00:00Z",
  },
  {
    id: "p-2",
    studioId: "studio-1",
    name: "Saanvi Portraits",
    clientId: "c-2",
    clientName: "Saanvi Malhotra",
    clientEmail: "saanvi.m@outlook.com",
    clientPhone: "+91 98765 43210",
    eventType: "Editorial Portrait",
    eventDate: "2026-10-05",
    venue: "Studio Colaba, Mumbai",
    status: "Awaiting payment",
    assignedPhotographer: "Vikram Rathore",
    assignedEditor: "Pooja Verma",
    quotationId: "q-2",
    quotationAmount: 35000,
    paidAmount: 20000,
    balanceAmount: 15000,
    galleryId: "g-2",
    deliveryDeadline: "2026-10-20",
    notes: "Client finished 25 photo selections! UTR submitted and awaiting verification.",
    checklist: {
      contractAccepted: true,
      advanceReceived: true,
      shootCompleted: true,
      photosBackedUp: true,
      cullingCompleted: true,
      editingCompleted: true,
      galleryUploaded: true,
      clientSelectionReceived: true,
      finalPaymentReceived: false,
      originalsDelivered: false,
    },
    photoCount: 86,
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-09-21T15:00:00Z",
  },
  {
    id: "p-3",
    studioId: "studio-1",
    name: "Nair · Reception",
    clientId: "c-3",
    clientName: "Isha & Aditya Nair",
    clientEmail: "isha.aditya@gmail.com",
    clientPhone: "+91 99300 88776",
    eventType: "Wedding & Reception",
    eventDate: "2026-07-24",
    venue: "Grand Hyatt Goa",
    status: "Delivered",
    assignedPhotographer: "Arjun Mehta",
    assignedEditor: "Pooja Verma",
    quotationId: "q-3",
    quotationAmount: 240000,
    paidAmount: 240000,
    balanceAmount: 0,
    galleryId: "g-3",
    deliveryDeadline: "2026-08-20",
    notes: "All 412 master photos delivered. Physical heirloom albums printed and handed over.",
    checklist: {
      contractAccepted: true,
      advanceReceived: true,
      shootCompleted: true,
      photosBackedUp: true,
      cullingCompleted: true,
      editingCompleted: true,
      galleryUploaded: true,
      clientSelectionReceived: true,
      finalPaymentReceived: true,
      originalsDelivered: true,
    },
    photoCount: 412,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-08-30T12:00:00Z",
  },
  {
    id: "p-4",
    studioId: "studio-1",
    name: "Mehra · Wedding",
    clientId: "c-4",
    clientName: "Tara & Rohan Mehra",
    clientEmail: "tara.mehra@yahoo.com",
    clientPhone: "+91 98199 55443",
    eventType: "Royal Wedding 3-Day",
    eventDate: "2026-11-12",
    venue: "Umaid Bhawan Palace, Jodhpur",
    status: "Editing",
    assignedPhotographer: "Arjun Mehta",
    assignedEditor: "Pooja Verma",
    quotationId: "q-4",
    quotationAmount: 380000,
    paidAmount: 150000,
    balanceAmount: 230000,
    galleryId: "g-4",
    deliveryDeadline: "2026-12-01",
    notes: "RAW files backed up to dual external NVMe drives. Color grading in progress.",
    checklist: {
      contractAccepted: true,
      advanceReceived: true,
      shootCompleted: false,
      photosBackedUp: false,
      cullingCompleted: false,
      editingCompleted: false,
      galleryUploaded: false,
      clientSelectionReceived: false,
      finalPaymentReceived: false,
      originalsDelivered: false,
    },
    photoCount: 520,
    createdAt: "2026-07-15T08:00:00Z",
    updatedAt: "2026-09-20T18:00:00Z",
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: "q-1",
    studioId: "studio-1",
    clientId: "c-1",
    clientName: "Rhea & Kabir Kapur",
    clientPhone: "+91 98200 11223",
    clientEmail: "rhea.kapur@gmail.com",
    projectId: "p-1",
    projectName: "Kapur · Mehendi & Sangeet",
    eventType: "Mehendi & Sangeet",
    eventDate: "2026-10-18",
    venue: "The St. Regis Mumbai · Astor Ballroom",
    items: [
      {
        id: "qi-1",
        description: "Wedding Day & Sangeet Dual Candid Photography Coverage",
        category: "Photography",
        quantity: 1,
        unitPrice: 85000,
        totalPrice: 85000,
      },
      {
        id: "qi-2",
        description: "Cinematic 4K Highlight Film (3-5 mins + Teaser)",
        category: "Cinematography",
        quantity: 1,
        unitPrice: 42000,
        totalPrice: 42000,
      },
      {
        id: "qi-3",
        description: "Premium Fine Art Heirloom Album (40 Spreads, Leatherbound)",
        category: "Album",
        quantity: 1,
        unitPrice: 28000,
        totalPrice: 28000,
      },
      {
        id: "qi-4",
        description: "Drone Aerial Coverage for Terrace Entry & Sangeet",
        category: "Drone",
        quantity: 1,
        unitPrice: 12000,
        totalPrice: 12000,
      },
      {
        id: "qi-5",
        description: "Same-Day Teaser Reel for Instagram within 24 hours",
        category: "Social",
        quantity: 1,
        unitPrice: 20000,
        totalPrice: 20000,
      },
    ],
    subtotal: 187000,
    discountPercentage: 0,
    discountAmount: 2000, // Round off courtesy
    includeGst: false,
    gstRate: 18,
    gstAmount: 0,
    grandTotal: 185000,
    advanceAmount: 95000,
    remainingBalance: 90000,
    milestones: [
      {
        title: "Booking Advance to Reserve Dates",
        percentage: 50,
        amount: 95000,
        dueDate: "2026-08-05",
        status: "paid",
      },
      {
        title: "On Completion of Shoot & Proofing Gallery Release",
        percentage: 30,
        amount: 55000,
        dueDate: "2026-10-19",
        status: "pending",
      },
      {
        title: "Prior to Final High-Res Master Deliverables & Album Print",
        percentage: 20,
        amount: 35000,
        dueDate: "2026-11-05",
        status: "pending",
      },
    ],
    status: "Accepted",
    validUntil: "2026-08-15",
    terms:
      "1. 50% advance secures date exclusively.\n2. Raw files remain property of UIKEY AI Studio; high-res curated JPEGs delivered after final payment.\n3. Travel and accommodation covered by client outside Mumbai.",
    notes: "Special package for Rhea & Kabir. Includes 1-minute vertical reel.",
    createdAt: "2026-08-01T10:30:00Z",
    viewedAt: "2026-08-02T11:15:00Z",
    acceptedAt: "2026-08-03T16:00:00Z",
  },
  {
    id: "q-2",
    studioId: "studio-1",
    clientId: "c-2",
    clientName: "Saanvi Malhotra",
    clientPhone: "+91 98765 43210",
    clientEmail: "saanvi.m@outlook.com",
    projectId: "p-2",
    projectName: "Saanvi Portraits",
    eventType: "Editorial Portrait",
    eventDate: "2026-10-05",
    venue: "Studio Colaba, Mumbai",
    items: [
      {
        id: "qi-6",
        description: "Studio Editorial & Lifestyle Portrait Session (3 Outfits)",
        category: "Photography",
        quantity: 1,
        unitPrice: 25000,
        totalPrice: 25000,
      },
      {
        id: "qi-7",
        description: "Professional Hair & Makeup Artist on Set",
        category: "Styling",
        quantity: 1,
        unitPrice: 10000,
        totalPrice: 10000,
      },
    ],
    subtotal: 35000,
    discountPercentage: 0,
    discountAmount: 0,
    includeGst: false,
    gstRate: 18,
    gstAmount: 0,
    grandTotal: 35000,
    advanceAmount: 20000,
    remainingBalance: 15000,
    milestones: [
      {
        title: "Booking Deposit",
        percentage: 57,
        amount: 20000,
        dueDate: "2026-08-25",
        status: "paid",
      },
      {
        title: "Final High-Res Retouched Images Delivery",
        percentage: 43,
        amount: 15000,
        dueDate: "2026-10-20",
        status: "pending",
      },
    ],
    status: "Accepted",
    validUntil: "2026-08-28",
    terms: "25 master retouched high-res images included with commercial portfolio rights.",
    notes: "Client has submitted UTR for remaining 15,000.",
    createdAt: "2026-08-20T11:30:00Z",
    viewedAt: "2026-08-20T14:00:00Z",
    acceptedAt: "2026-08-21T09:00:00Z",
  },
  {
    id: "q-5",
    studioId: "studio-1",
    clientId: "c-5",
    clientName: "Ananya Deshmukh",
    clientPhone: "+91 98211 44778",
    clientEmail: "ananya.d@gmail.com",
    projectName: "Deshmukh Pre-wedding Celebration",
    eventType: "Pre-wedding Shoot",
    eventDate: "2026-10-29",
    venue: "South Mumbai Heritage Precinct",
    items: [
      {
        id: "qi-8",
        description: "Pre-wedding sunset session (South Mumbai + Bandra Fort)",
        category: "Photography",
        quantity: 1,
        unitPrice: 18000,
        totalPrice: 18000,
      },
      {
        id: "qi-9",
        description: "Cinematic 4K 60fps Music Video Highlight",
        category: "Cinematography",
        quantity: 1,
        unitPrice: 20000,
        totalPrice: 20000,
      },
      {
        id: "qi-10",
        description: "Licensed Drone Aerial Sequences",
        category: "Drone",
        quantity: 1,
        unitPrice: 7000,
        totalPrice: 7000,
      },
    ],
    subtotal: 45000,
    discountPercentage: 0,
    discountAmount: 0,
    includeGst: true,
    gstRate: 18,
    gstAmount: 8100,
    grandTotal: 53100,
    advanceAmount: 25000,
    remainingBalance: 28100,
    milestones: [
      {
        title: "Date Confirmation Advance",
        percentage: 50,
        amount: 25000,
        dueDate: "2026-09-30",
        status: "pending",
      },
      {
        title: "On Final Gallery Handover",
        percentage: 50,
        amount: 28100,
        dueDate: "2026-11-15",
        status: "pending",
      },
    ],
    status: "Sent",
    validUntil: "2026-10-05",
    terms: "Permits for Mumbai heritage sites to be facilitated by client if required.",
    notes: "Proposal shared via WhatsApp wa.me link.",
    createdAt: "2026-09-21T10:00:00Z",
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    studioId: "studio-1",
    projectId: "p-2",
    projectName: "Saanvi Portraits",
    clientId: "c-2",
    clientName: "Saanvi Malhotra",
    clientPhone: "+91 98765 43210",
    amount: 15000,
    milestoneTitle: "Final High-Res Retouched Images Delivery",
    upiId: "uikeystudio@upi",
    utrNumber: "426189033412",
    receiptUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
    status: "UTR submitted",
    submittedAt: "2026-09-21T16:45:00Z",
    internalNote: "Paid via Google Pay. Need to verify in HDFC current account.",
    downloadsUnlocked: false,
    createdAt: "2026-09-21T16:45:00Z",
  },
  {
    id: "pay-2",
    studioId: "studio-1",
    projectId: "p-1",
    projectName: "Kapur · Mehendi",
    clientId: "c-1",
    clientName: "Rhea & Kabir Kapur",
    clientPhone: "+91 98200 11223",
    amount: 95000,
    milestoneTitle: "Booking Advance to Reserve Dates",
    upiId: "uikeystudio@upi",
    utrNumber: "421589129045",
    receiptUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80",
    status: "Verified",
    submittedAt: "2026-08-04T12:30:00Z",
    verifiedAt: "2026-08-04T13:00:00Z",
    internalNote: "Advance credited in full.",
    downloadsUnlocked: false, // Proofing only
    createdAt: "2026-08-04T12:30:00Z",
  },
  {
    id: "pay-3",
    studioId: "studio-1",
    projectId: "p-3",
    projectName: "Nair · Reception",
    clientId: "c-3",
    clientName: "Isha & Aditya Nair",
    clientPhone: "+91 99300 88776",
    amount: 100000,
    milestoneTitle: "Final Master Delivery & Album Print",
    upiId: "uikeystudio@upi",
    utrNumber: "420199847123",
    receiptUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
    status: "Verified",
    submittedAt: "2026-08-18T10:00:00Z",
    verifiedAt: "2026-08-18T11:15:00Z",
    internalNote: "Final settlement completed. Original master downloads unlocked.",
    downloadsUnlocked: true,
    createdAt: "2026-08-18T10:00:00Z",
  },
];

// ============================================================================
// REALISTIC CONTRACTS & SERVICE AGREEMENTS (INDIAN WEDDINGS)
// ============================================================================

export const DEFAULT_CONTRACT_CLAUSES: ContractClause[] = [
  {
    id: "cl-1",
    title: "1. Scope of Coverage & Event Timing",
    content:
      "The Studio agrees to provide professional photography and cinematography services for the designated dates, venues, and events listed herein. Any extension beyond scheduled shift hours will be billed at standard overtime rates (₹3,000/hr per crew member) with prior verbal concurrence.",
    isRequired: true,
  },
  {
    id: "cl-2",
    title: "2. Payment Milestones & Bharat UPI Protocol",
    content:
      "A booking advance of 20% is required to reserve the dates exclusively. 60% is payable 48 hours before the principal shoot date. The final 20% balance is payable upon notification of edit completion and prior to delivery of master high-resolution files or album printing. All payments are made via official Bharat UPI or verified bank transfer with a valid 12-digit UTR.",
    isRequired: true,
  },
  {
    id: "cl-3",
    title: "3. Delivery Timeline & Quality Handover",
    content:
      "Digital watermarked proofing gallery will be delivered within 14 calendar days of shoot conclusion for client selection. Upon receipt of final client selections, color-graded and retouched high-resolution images will be delivered within 30 to 45 days. Hardcover flush-mount albums (if contracted) require an additional 21 days for physical print binding and courier dispatch.",
    isRequired: true,
  },
  {
    id: "cl-4",
    title: "4. RAW Camera Files Policy",
    content:
      "In accordance with standard industry practice, raw unprocessed camera digital negative files (CR3/ARW/NEF/LOG) are proprietary archival assets of the Studio and are not included in standard deliverables. Client receives master full-resolution color-corrected JPEGs and edited 4K video exports.",
    isRequired: true,
  },
  {
    id: "cl-5",
    title: "5. Crew Hospitality & Outstation Travel",
    content:
      "For events exceeding 4 continuous hours, Client shall provide hot meals and drinking water for all assigned crew members. For outstation destination assignments, Client shall provide hotel accommodation (minimum 3-star standard) and round-trip transportation/flights for the crew.",
    isRequired: true,
  },
  {
    id: "cl-6",
    title: "6. Drone Operations & Venue Permissions",
    content:
      "Aerial drone videography is subject to prevailing weather, local airspace regulations (DGCA Red/Yellow zones), and venue permissions. The Studio cannot be held liable if venue management, heritage authorities, or local police prohibit drone flights.",
    isRequired: false,
  },
  {
    id: "cl-7",
    title: "7. Postponement & Cancellation",
    content:
      "The 20% booking advance is non-refundable as the Studio declines other prospective inquiries for reserved dates. In case of genuine unforeseen events or force majeure, client may postpone the dates once within 6 months at no penalty, subject to mutual date availability.",
    isRequired: true,
  },
  {
    id: "cl-8",
    title: "8. Copyright & Studio Portfolio Usage",
    content:
      "The Client is granted perpetual, non-exclusive rights for personal reproduction, printing, and social media sharing. The Studio reserves the moral copyright and artistic right to showcase selected photographs in its professional portfolio, website, and competition entries, with due respect to client privacy.",
    isRequired: true,
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: "con-1",
    contractNumber: "CON-2026-001",
    studioId: "studio-1",
    projectId: "p-1",
    projectName: "Kapur · Mehendi & Wedding",
    clientId: "c-1",
    clientName: "Rhea & Kabir Kapur",
    clientPhone: "+91 98200 11223",
    clientEmail: "rhea.kapur@gmail.com",
    status: "signed",
    totalAmount: 190000,
    advanceAmount: 95000,
    eventDates: ["2026-11-14", "2026-11-15"],
    venues: ["The Taj Mahal Palace, Colaba, Mumbai", "Bayview Lawns, Mazgaon"],
    deliverables: [
      "Traditional & Candid Photography (2 Photographers)",
      "Cinematic 4K Wedding Film (3-5 mins highlight + 45 min full film)",
      "Premium 40-sheet Leatherette Flush Mount Album (12x36)",
      "Watermarked Online Proofing Gallery with Selection Tool",
      "Full Resolution Color Graded Master JPEGs on Cloud Drive",
    ],
    rawFilesPolicy: "Master high-resolution JPEGs delivered. RAW digital negatives retained by studio.",
    travelTerms: "Local Mumbai assignment. Meals provided on venue.",
    cancellationPolicy: "20% non-refundable advance. Date postponement permitted with 30-day notice.",
    clauses: DEFAULT_CONTRACT_CLAUSES,
    signedByName: "Kabir Kapur",
    signedAt: "2026-08-04T13:15:00Z",
    signatureDataUrl:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='60'><path d='M10 40 Q 50 10, 90 35 T 180 20' stroke='%23C4B5FD' fill='none' stroke-width='3'/></svg>",
    clientIp: "103.21.124.89",
    createdAt: "2026-08-03T10:00:00Z",
    updatedAt: "2026-08-04T13:15:00Z",
  },
  {
    id: "con-2",
    contractNumber: "CON-2026-002",
    studioId: "studio-1",
    projectId: "p-2",
    projectName: "Saanvi Portraits",
    clientId: "c-2",
    clientName: "Saanvi Malhotra",
    clientPhone: "+91 98765 43210",
    clientEmail: "saanvi.m@outlook.com",
    status: "signed",
    totalAmount: 35000,
    advanceAmount: 20000,
    eventDates: ["2026-09-02"],
    venues: ["Studio 4, Bandra West, Mumbai"],
    deliverables: [
      "3-hour Fashion / Fine-Art Portrait Session",
      "25 Master Retouched High-Resolution Files",
      "Online Proofing Gallery with 150 Watermarked Previews",
      "Commercial & Social Media Portfolio Usage Rights",
    ],
    rawFilesPolicy: "25 retouched master JPEGs delivered. Additional retouched images @ ₹800/image.",
    travelTerms: "In-studio shoot.",
    cancellationPolicy: "Advance non-refundable. Rescheduling permitted once with 48-hr notice.",
    clauses: DEFAULT_CONTRACT_CLAUSES,
    signedByName: "Saanvi Malhotra",
    signedAt: "2026-08-21T09:30:00Z",
    signatureDataUrl:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='60'><path d='M10 45 Q 60 5, 110 30 T 190 25' stroke='%23C4B5FD' fill='none' stroke-width='3'/></svg>",
    clientIp: "115.99.14.22",
    createdAt: "2026-08-20T11:45:00Z",
    updatedAt: "2026-08-21T09:30:00Z",
  },
  {
    id: "con-3",
    contractNumber: "CON-2026-003",
    studioId: "studio-1",
    projectId: "p-4",
    projectName: "Mehra · Wedding Extravaganza",
    clientId: "c-4",
    clientName: "Pooja & Sameer Mehra",
    clientPhone: "+91 98190 66554",
    clientEmail: "pooja.mehra@gmail.com",
    status: "sent",
    totalAmount: 280000,
    advanceAmount: 70000,
    eventDates: ["2026-12-18", "2026-12-19", "2026-12-20"],
    venues: ["ITC Grand Central, Parel, Mumbai", "St. Regis Mumbai, Lower Parel"],
    deliverables: [
      "Full 3-Day Wedding Coverage (Sangeet, Phere, Reception)",
      "4-person crew: 2 Candid Photographers, 1 Traditional Videographer, 1 Drone Specialist",
      "4K Cinematic Film (5 min teaser + 60 min narrative documentary)",
      "Two Premium 12x36 Handcrafted Flush Mount Leather Albums (50 sheets each)",
      "Fast-Track 10-day Selection Proofing Gallery with Watermarking",
      "Archival Delivery on Custom Wooden USB + Permanent Cloud Gallery",
    ],
    rawFilesPolicy: "All color graded final master JPEGs delivered on USB + Cloud. RAWs excluded.",
    travelTerms: "Mumbai venue hospitality and crew hot meals to be arranged by client.",
    cancellationPolicy: "20% advance non-refundable to hold dates.",
    clauses: DEFAULT_CONTRACT_CLAUSES,
    createdAt: "2026-09-15T14:20:00Z",
    updatedAt: "2026-09-15T14:20:00Z",
  },
];

// ============================================================================
// REALISTIC TAX INVOICES & RECEIPTS (GST SAC 998381)
// ============================================================================

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "INV-2026-001",
    studioId: "studio-1",
    projectId: "p-1",
    projectName: "Kapur · Mehendi",
    clientId: "c-1",
    clientName: "Rhea & Kabir Kapur",
    clientPhone: "+91 98200 11223",
    clientEmail: "rhea.kapur@gmail.com",
    clientAddress: "Altamount Road, Mumbai, Maharashtra 400026",
    items: [
      {
        id: "ii-1",
        description: "Booking Advance: 2-Day Candid Photography & Cinematic Highlights (SAC 998381)",
        sacCode: "998381",
        quantity: 1,
        unitPrice: 80508,
        totalPrice: 80508,
      },
    ],
    subtotal: 80508,
    includeGst: true,
    gstRate: 18,
    cgstAmount: 7246,
    sgstAmount: 7246,
    igstAmount: 0,
    grandTotal: 95000,
    paidAmount: 95000,
    balanceDue: 0,
    dueDate: "2026-08-05",
    status: "paid",
    upiId: "uikeystudio@upi",
    bankDetails: {
      bankName: "HDFC Bank Ltd",
      accountNumber: "50200084729104",
      ifscCode: "HDFC0000019",
      accountName: "UIKEY AI STUDIO LLP",
      branch: "Fort Branch, Mumbai",
    },
    notes: "Payment received via Bharat UPI (UTR: 421589129045). Thank you for your business!",
    terms: "Official Tax Receipt for Commercial & Event Photography Services. HSN/SAC 998381.",
    createdAt: "2026-08-04T13:00:00Z",
  },
  {
    id: "inv-2",
    invoiceNumber: "INV-2026-002",
    studioId: "studio-1",
    projectId: "p-3",
    projectName: "Nair · Reception",
    clientId: "c-3",
    clientName: "Isha & Aditya Nair",
    clientPhone: "+91 99300 88776",
    clientEmail: "isha.nair@gmail.com",
    clientAddress: "Hiranandani Gardens, Powai, Mumbai 400076",
    items: [
      {
        id: "ii-2",
        description: "Complete Wedding & Reception Photography Package (SAC 998381)",
        sacCode: "998381",
        quantity: 1,
        unitPrice: 152542,
        totalPrice: 152542,
      },
    ],
    subtotal: 152542,
    includeGst: true,
    gstRate: 18,
    cgstAmount: 13729,
    sgstAmount: 13729,
    igstAmount: 0,
    grandTotal: 180000,
    paidAmount: 180000,
    balanceDue: 0,
    dueDate: "2026-08-18",
    status: "paid",
    upiId: "uikeystudio@upi",
    bankDetails: {
      bankName: "HDFC Bank Ltd",
      accountNumber: "50200084729104",
      ifscCode: "HDFC0000019",
      accountName: "UIKEY AI STUDIO LLP",
      branch: "Fort Branch, Mumbai",
    },
    notes: "Full payment settled via Bharat UPI (UTR: 420199847123). Master files unlocked.",
    terms: "Tax Invoice issued per GST Act 2017. Photographic and Videographic Services.",
    createdAt: "2026-08-18T11:30:00Z",
  },
];

// SAMPLE HIGH-RES UNSPLASH PHOTOGRAPHY FOR PROOFING GALLERIES
const SAMPLE_GALLERY_IMAGES: GalleryImage[] = [
  {
    id: "img-1",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_001.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=4000&auto=format&fit=crop&q=95",
    category: "Bridal Details",
    selectionState: "favorite",
    comments: [
      {
        id: "comm-1",
        imageId: "img-1",
        authorName: "Rhea Kapur",
        text: "Please keep this for the opening spread of the album!",
        createdAt: "2026-09-21T18:00:00Z",
      },
    ],
    width: 2400,
    height: 3600,
    aspectRatio: 0.66,
    fileSizeBytes: 14200000,
    hidden: false,
  },
  {
    id: "img-2",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_002.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=4000&auto=format&fit=crop&q=95",
    category: "Mehendi Art",
    selectionState: "favorite",
    comments: [],
    width: 3600,
    height: 2400,
    aspectRatio: 1.5,
    fileSizeBytes: 18500000,
    hidden: false,
  },
  {
    id: "img-3",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_003.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=4000&auto=format&fit=crop&q=95",
    category: "Couple Portraits",
    selectionState: "unrated",
    comments: [],
    width: 2400,
    height: 3000,
    aspectRatio: 0.8,
    fileSizeBytes: 12400000,
    hidden: false,
  },
  {
    id: "img-4",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_004.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=4000&auto=format&fit=crop&q=95",
    category: "Couple Portraits",
    selectionState: "favorite",
    comments: [],
    width: 3600,
    height: 2400,
    aspectRatio: 1.5,
    fileSizeBytes: 16800000,
    hidden: false,
  },
  {
    id: "img-5",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_005.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=4000&auto=format&fit=crop&q=95",
    category: "Sangeet Energy",
    selectionState: "maybe",
    comments: [],
    width: 2400,
    height: 3600,
    aspectRatio: 0.66,
    fileSizeBytes: 15300000,
    hidden: false,
  },
  {
    id: "img-6",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_006.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=4000&auto=format&fit=crop&q=95",
    category: "Family & Candid",
    selectionState: "unrated",
    comments: [],
    width: 3600,
    height: 2400,
    aspectRatio: 1.5,
    fileSizeBytes: 14100000,
    hidden: false,
  },
  {
    id: "img-7",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_007.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=4000&auto=format&fit=crop&q=95",
    category: "Sangeet Energy",
    selectionState: "reject",
    comments: [],
    width: 3600,
    height: 2400,
    aspectRatio: 1.5,
    fileSizeBytes: 13900000,
    hidden: false,
  },
  {
    id: "img-8",
    galleryId: "g-1",
    filename: "KAPUR_MEHENDI_008.JPG",
    thumbnailUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=450&auto=format&fit=crop&q=80",
    previewUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=1600&auto=format&fit=crop&q=85",
    originalUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=4000&auto=format&fit=crop&q=95",
    category: "Bridal Details",
    selectionState: "favorite",
    comments: [],
    width: 2400,
    height: 3200,
    aspectRatio: 0.75,
    fileSizeBytes: 15900000,
    hidden: false,
  },
];

export const INITIAL_GALLERIES: Gallery[] = [
  {
    id: "g-1",
    studioId: "studio-1",
    projectId: "p-1",
    projectName: "Kapur · Mehendi",
    clientName: "Rhea & Kabir Kapur",
    clientEmail: "rhea.kapur@gmail.com",
    clientToken: "kapur-mehendi-token",
    status: "Selection in progress",
    watermarkText: "PROOF ONLY · UIKEY AI STUDIO",
    watermarkOpacity: 0.28,
    categories: [
      { id: "all", name: "All Photos", count: 238 },
      { id: "bridal", name: "Bridal Details", count: 42 },
      { id: "couple", name: "Couple Portraits", count: 68 },
      { id: "mehendi", name: "Mehendi Art", count: 34 },
      { id: "sangeet", name: "Sangeet Energy", count: 64 },
      { id: "family", name: "Family & Candid", count: 30 },
    ],
    totalImages: 238,
    selectedCount: 4,
    rejectedCount: 1,
    maybeCount: 1,
    requiredSelectionCount: 80,
    isSelectionSubmitted: false,
    downloadsUnlocked: false,
    expiryDate: "2026-11-20",
    createdAt: "2026-09-18T14:00:00Z",
  },
  {
    id: "g-2",
    studioId: "studio-1",
    projectId: "p-2",
    projectName: "Saanvi Portraits",
    clientName: "Saanvi Malhotra",
    clientEmail: "saanvi.m@outlook.com",
    clientToken: "saanvi-portraits-token",
    status: "Selection submitted",
    watermarkText: "PROOF ONLY · UIKEY AI STUDIO",
    watermarkOpacity: 0.28,
    categories: [
      { id: "all", name: "All Photos", count: 86 },
      { id: "studio", name: "Studio Editorial", count: 50 },
      { id: "bw", name: "Monochrome Black & White", count: 36 },
    ],
    totalImages: 86,
    selectedCount: 25,
    rejectedCount: 12,
    maybeCount: 8,
    requiredSelectionCount: 25,
    isSelectionSubmitted: true,
    submittedAt: "2026-09-21T15:30:00Z",
    downloadsUnlocked: false, // will unlock when payment pay-1 is verified
    expiryDate: "2026-10-31",
    createdAt: "2026-09-10T10:00:00Z",
  },
  {
    id: "g-3",
    studioId: "studio-1",
    projectId: "p-3",
    projectName: "Nair · Reception",
    clientName: "Isha & Aditya Nair",
    clientEmail: "isha.aditya@gmail.com",
    clientToken: "nair-reception-token",
    status: "Approved",
    watermarkText: "PROOF ONLY · UIKEY AI STUDIO",
    watermarkOpacity: 0.28,
    categories: [
      { id: "all", name: "All Photos", count: 412 },
      { id: "wedding", name: "Sunset Mandap", count: 180 },
      { id: "reception", name: "Beachside Gala", count: 232 },
    ],
    totalImages: 412,
    selectedCount: 150,
    rejectedCount: 40,
    maybeCount: 20,
    requiredSelectionCount: 150,
    isSelectionSubmitted: true,
    downloadsUnlocked: true, // Fully unlocked
    expiryDate: "2026-12-31",
    createdAt: "2026-08-01T12:00:00Z",
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "cal-1",
    studioId: "studio-1",
    title: "Kapur · Mehendi Shoot",
    type: "shoot",
    date: "2026-10-18",
    venue: "The St. Regis Mumbai · Astor Ballroom",
    clientName: "Rhea & Kabir Kapur",
    projectId: "p-1",
    assignedTo: "Arjun Mehta",
    status: "Booked",
  },
  {
    id: "cal-2",
    studioId: "studio-1",
    title: "Deshmukh Pre-wedding Consultation",
    type: "meeting",
    date: "2026-10-20",
    venue: "Google Meet / Studio",
    clientName: "Ananya Deshmukh",
    status: "Tentative",
  },
  {
    id: "cal-3",
    studioId: "studio-1",
    title: "Saanvi Portraits Retouch Deadline",
    type: "editing_deadline",
    date: "2026-10-20",
    clientName: "Saanvi Malhotra",
    projectId: "p-2",
    assignedTo: "Pooja Verma",
    status: "Booked",
  },
  {
    id: "cal-4",
    studioId: "studio-1",
    title: "Mehra Wedding · Day 1 Mehendi (Jodhpur)",
    type: "shoot",
    date: "2026-11-12",
    venue: "Umaid Bhawan Palace, Jodhpur",
    clientName: "Tara & Rohan Mehra",
    projectId: "p-4",
    assignedTo: "Arjun Mehta + Full Crew",
    status: "Booked",
  },
  {
    id: "cal-5",
    studioId: "studio-1",
    title: "Mehra Wedding · Day 2 Sangeet (Jodhpur)",
    type: "shoot",
    date: "2026-11-13",
    venue: "Umaid Bhawan Palace, Jodhpur",
    clientName: "Tara & Rohan Mehra",
    projectId: "p-4",
    assignedTo: "Arjun Mehta + Full Crew",
    status: "Booked",
  },
  {
    id: "cal-6",
    studioId: "studio-1",
    title: "Mehra Wedding · Day 3 Royal Pheras (Jodhpur)",
    type: "shoot",
    date: "2026-11-14",
    venue: "Umaid Bhawan Palace, Jodhpur",
    clientName: "Tara & Rohan Mehra",
    projectId: "p-4",
    assignedTo: "Arjun Mehta + Full Crew",
    status: "Booked",
  },
  {
    id: "cal-7",
    studioId: "studio-1",
    title: "Travel Day: Mumbai to Jodhpur",
    type: "shoot",
    date: "2026-11-11",
    clientName: "Internal Crew",
    status: "Travel day",
  },
];

export const INITIAL_PORTFOLIO: PortfolioProfile = {
  username: "arjun-mehta",
  studioName: "UIKEY AI Studio",
  photographerName: "Arjun Mehta",
  bio: "Celebrated destination wedding and editorial photographer based out of Mumbai and Goa. Documenting quiet moments of intimacy and grand festivities with deep emotional resonance, natural light, and cinematic storytelling.",
  city: "Mumbai",
  serviceArea: "Mumbai · Goa · Udaipur · Worldwide",
  heroImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&auto=format&fit=crop&q=85",
  instagramUrl: "https://instagram.com/uikey_studio",
  whatsappNumber: "+91 98201 98201",
  startingPrice: 85000,
  availableForTravel: true,
  categories: ["Weddings", "Pre-weddings", "Portraits", "Fashion", "Editorial"],
  testimonials: [
    {
      clientName: "Isha & Aditya Nair",
      event: "Goa Beach Wedding",
      quote:
        "Arjun and his team felt like family. Looking through our proofing gallery brought back every single tear and laugh. UIKEY AI Studio made selecting our album photos on our phones ridiculously easy!",
      rating: 5,
    },
    {
      clientName: "Saanvi Malhotra",
      event: "Editorial Campaign",
      quote:
        "The professionalism and color grading are world-class. From reviewing the quotation with milestone payments to downloading the final high-res files, the workflow was flawless.",
      rating: 5,
    },
    {
      clientName: "Rhea Kapur",
      event: "Mehendi & Sangeet",
      quote:
        "The proofing gallery with diagonal watermarks gave our family complete peace of mind while choosing our favorites. Hands down the best wedding photography experience in India.",
      rating: 5,
    },
  ],
  services: [
    {
      title: "Wedding Day Signature Coverage",
      price: "₹85,000",
      description: "Comprehensive 2-photographer candid and traditional documentary storytelling for your big day.",
      features: [
        "10–12 Hours Comprehensive Coverage",
        "2 Senior Candid Photographers",
        "Private Online Proofing Portal",
        "500+ High-Resolution Master JPEGs",
        "Teaser Reel delivered in 48 hours",
      ],
    },
    {
      title: "Pre-Wedding Cinematic Session",
      price: "₹18,000",
      description: "Intimate editorial session at curated heritage or coastal locations before your festivities.",
      features: [
        "4 Hours Golden Hour Shoot",
        "Up to 3 Outfit Changes",
        "40 Finely Retouched Master Deliverables",
        "Fast 7-Day Turnaround",
      ],
    },
    {
      title: "Cinematic 4K Highlight Film",
      price: "₹42,000",
      description: "Emotionally evocative film paired with ambient audio, speeches, and licensed orchestral music.",
      features: [
        "Dedicated Cinematographer & Drone Pilot",
        "3–5 Minute 4K Master Film",
        "60-Second Social Media Teaser",
        "Raw Speeches & Toast Audio Recording",
      ],
    },
  ],
};

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    studioId: "studio-1",
    title: "Payment Submitted via UPI",
    message: "Saanvi Malhotra submitted ₹15,000 with UTR 426189033412. Please verify receipt.",
    type: "payment",
    linkUrl: "/dashboard/payments",
    read: false,
    createdAt: "2026-09-21T16:45:00Z",
  },
  {
    id: "notif-2",
    studioId: "studio-1",
    title: "Gallery Selection Submitted",
    message: "Saanvi Malhotra finalized 25 photo picks for Saanvi Portraits.",
    type: "gallery",
    linkUrl: "/dashboard/galleries/g-2",
    read: false,
    createdAt: "2026-09-21T15:30:00Z",
  },
  {
    id: "notif-3",
    studioId: "studio-1",
    title: "New Portfolio Inquiry",
    message: "Ananya Deshmukh inquired for Pre-wedding shoot in South Mumbai (₹45,000 budget).",
    type: "inquiry",
    linkUrl: "/dashboard/clients/c-5",
    read: true,
    createdAt: "2026-09-21T09:30:00Z",
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "act-1",
    studioId: "studio-1",
    actorName: "Arjun Mehta",
    action: "Uploaded 238 proofing photos to",
    target: "Kapur · Mehendi Gallery",
    timestamp: "2026-09-18T14:00:00Z",
  },
  {
    id: "act-2",
    studioId: "studio-1",
    actorName: "Saanvi Malhotra",
    action: "Submitted final selection (25 photos) for",
    target: "Saanvi Portraits",
    timestamp: "2026-09-21T15:30:00Z",
  },
  {
    id: "act-3",
    studioId: "studio-1",
    actorName: "Saanvi Malhotra",
    action: "Submitted UPI UTR 426189033412 for",
    target: "₹15,000 Final Milestone",
    timestamp: "2026-09-21T16:45:00Z",
  },
  {
    id: "act-4",
    studioId: "studio-1",
    actorName: "Arjun Mehta",
    action: "Generated & sent quotation for",
    target: "Ananya Deshmukh (₹53,100)",
    timestamp: "2026-09-21T10:00:00Z",
  },
];

// Initial storage usage: 14.8 GB used out of 50 GB standard plan
export const INITIAL_STORAGE_USAGE: StorageUsage = {
  totalBytes: 14.8 * 1024 * 1024 * 1024,
  quotaBytes: STORAGE_PLANS.standard.quotaBytes,
  percentage: Math.round((14.8 / 50) * 100),
  warningLevel: calculateStorageWarning(14.8 * 1024 * 1024 * 1024, STORAGE_PLANS.standard.quotaBytes),
  previewBytes: 4.2 * 1024 * 1024 * 1024,
  originalBytes: 9.8 * 1024 * 1024 * 1024,
  thumbnailsBytes: 0.6 * 1024 * 1024 * 1024,
  receiptsBytes: 0.2 * 1024 * 1024 * 1024,
  bandwidthBytes: 8.5 * 1024 * 1024 * 1024,
};

// ============================================================================
// REACTIVE CLIENT STORE (WITH LOCALSTORAGE BACKING)
// ============================================================================

export interface StudioStoreState {
  studio: Studio;
  team: TeamMember[];
  clients: Client[];
  projects: Project[];
  quotations: Quotation[];
  payments: Payment[];
  contracts: Contract[];
  invoices: Invoice[];
  galleries: Gallery[];
  galleryImages: Record<string, GalleryImage[]>; // keyed by galleryId
  calendarEvents: CalendarEvent[];
  portfolio: PortfolioProfile;
  notifications: Notification[];
  activityLogs: ActivityLog[];
  storageUsage: StorageUsage;
}

export const STORAGE_KEY = "uikey_studio_demo_state_v2";

export function getInitialState(): StudioStoreState {
  if (typeof window !== "undefined") {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        // Ensure contracts and invoices exist if migrating from v1
        if (!parsed.contracts) parsed.contracts = INITIAL_CONTRACTS;
        if (!parsed.invoices) parsed.invoices = INITIAL_INVOICES;
        return parsed;
      }
    } catch {
      // ignore
    }
  }

  return {
    studio: INITIAL_STUDIO,
    team: INITIAL_TEAM,
    clients: INITIAL_CLIENTS,
    projects: INITIAL_PROJECTS,
    quotations: INITIAL_QUOTATIONS,
    payments: INITIAL_PAYMENTS,
    contracts: INITIAL_CONTRACTS,
    invoices: INITIAL_INVOICES,
    galleries: INITIAL_GALLERIES,
    galleryImages: {
      "g-1": SAMPLE_GALLERY_IMAGES,
      "g-2": SAMPLE_GALLERY_IMAGES.slice(0, 5),
      "g-3": SAMPLE_GALLERY_IMAGES.slice(0, 6),
    },
    calendarEvents: INITIAL_CALENDAR_EVENTS,
    portfolio: INITIAL_PORTFOLIO,
    notifications: INITIAL_NOTIFICATIONS,
    activityLogs: INITIAL_ACTIVITY_LOGS,
    storageUsage: INITIAL_STORAGE_USAGE,
  };
}

export function saveState(state: StudioStoreState): void {
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch {
      // storage quota / unavailable
    }
  }
}
